config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to: "home#index"


  resource :contacts, only: [:new, :create, :show]

  resources :articles do
    resources :comments
  end

  get 'article/new'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]
  # before_action :authenticate_user
  def index
    @articles = Article.all
    @comments = Comment.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end


  def create
    @article = Article.new(article_params)
    if @article.valid?
      @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path

  end

  private

  def article_params
    params.require(:articles).permit(:title, :text)

  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)


    redirect_to article_path(@article)


  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)

  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end
  
  def show
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end

  end

  private

  def contact_params
    params.require(:contacts).permit(:email, :message)

  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def contacts
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def terms

  end


  def about
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/create.html.erb
<h1>Thanks to you</h1>
<h2>article was created</h2>
<a href="/articles">Show all our article   s
  <br>
<%= link_to 'Show all articles!!!', articles_path %>

app/views/articles/edit.html.erb
<div class="container">

  <div class="row">


    <h1>Edit Article</h1>
    <%= form_for :articles, url: article_path(@article), method: :put do |f| %>
      <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title  %>
      </p>

      <p>
        <%= f.label :text %> <br>
        <%= f.text_field :text  %>
      </p>
      <p>
        <%= f.submit %>
      </p>


    <% end %>

</div>
</div>

app/views/articles/index.html.erb
<div class="container">
    <div class="row">

      <div class="col-xs-4">
      </div>

      <div class="col-xs-8">
        <h2><i>List of articles</i></h2>
        <h4> <%= link_to 'add New article', new_article_path %> </h4>
      </div>

    </div>

  <div class="row">

    <div class="col-xs-2">
    </div>

    <div class="col-xs-8">
      <% @xxx = 1 %>

      <% @articles.each do |art| %>

        <h3><%= art.title %></h3>
        <p> <h4><%= art.text %></h4> </p>
        <p>
          <%= link_to 'Show', article_path(art) %>  |

          <%= link_to 'Edit', edit_article_path(art) %>  |

          <%= link_to 'Destroooooy', article_path(art), method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
        <i>
          <h3> comments.....</h3>
          <p>
            <% @comments.each do |com| %>

            <p></p>

            <% if com.article_id == @xxx %>


              <h6><%= com.author %> said-</h6>
              <p>

              <h6><%= com.body %></h6>
            <% end %>

          <% end %>
          <% @xxx = @xxx + 1 %>
        </i>
        <hr/>
      <% end %>
    </div>

    <div class="col-xs-2">
    </div>

  </div>

</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">

    <h1>let`s write new Article</h1>
    <%= form_for :articles, url: articles_path do |f| %>
      <p>
          <%= f.label :title %> <br>
          <%= f.text_field :title %>
      </p>

      <p>
        <%= f.label :text %> <br>
        <%= f.text_field :text  %>
      </p>
      <p>
        <%= f.submit %>
      </p>


    <% end %>


  </div>

</div>

app/views/articles/show.html.erb
 <div class="container">



    <h1><%= @article.title %></h1>
    <p><h2><%= @article.text %></h2></p>
    <i>
     <h3> Comments </h3>
      <% @article.comments.each do |com| %>
          <%= com.author %> said: <br />
          <p>
           <%= com.body %>
          </p>
      <% end %>
    </i>
    <%= form_for ([@article, @article.comments.build]) do |f| %>
      <p>
      <p>
        <%= f.label :author %> <br>
        <%= f.text_field :author  %>
      </p>

      <p>
        <%= f.label :body %> <br>
        <%= f.text_field :body  %>
      </p>
        <%= f.submit %>
      </p>


    <% end %>

 </div>

app/views/contacts/create.html.erb
<h1>Thanks to you!</h1>

app/views/contacts/new.html.erb
<!--1^38^00-->
<h1>Contact Us</h1>

<%= form_for :contacts, url: contact_path do |f| %>
  <% if @contact && @contact.errors.any?%>

    <p>
      <ul>
        <%= @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </p>
  <% end %>
  <p>
    <%= f.label :email %> <br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :message %> <br>
    <%= f.text_field :message %>
  </p>
  <p>
    <%= f.submit 'Send message' %>
  </p>


<% end %>

app/views/contacts/show.html.erb
<div class="container">
  <div class="row" >
    <div class="col-xs-2">
    </div>

    <div class="col-xs-10">

      <h2>you can call us</h2>
      <h3> 8-918-555-888-2 </h3>
      <br>
      <div id="cen1">
        <h3> or just visit us </h3>
      </div>
    </div>
  </div>

<div class="row">

  <div class="col-xs-2">
  </div>

  <div class="col-xs-8">
    <!--Google map-->
    <div id="map-container-google-2" class="z-depth-1-half map-container" style="height: 500px">
      <iframe src="https://maps.google.com/maps?q=krasnodar&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0"
        style="border:0" allowfullscreen></iframe>
    </div>

    <!--Google Maps-->
  </div>

  <div class="col-xs-2">
  </div>


</div>



</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogJour</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body
  <p> </p>

<div class="container">
    <div class="row">
        <div class="col-xs-6">
          <h4>
            <b>
            <% if user_signed_in? %>

              <%= current_user.email %>
              ...
              <%= current_user.username %>
              ___
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
              __
              <% else %>
            <%= link_to 'Sign in', new_user_session_path %>
            <% end %>
            </b>
          </h4>
        </div>

        <div class="col-xs-3">
        </div>

        <div class="col-xs-3">
          <div class="btn-group" role="group" aria-label="Basic example">

            <button type="button" class="btn btn-outline-secondary">Left</button>
            <button type="button" class="btn btn-outline-secondary">Middle</button>
            <button type="button" class="btn btn-outline-secondary">Right</button>
          </div>
        </div>
    </div>

  <br>



</div>

<div class="row">
    <div class="col-xs-3">
    </div>

    <div class="col-xs-6">

            <br>
            <h2> <%= link_to 'Articles list', articles_path %> | <%= link_to 'Contacts', contacts_path %> | <%= link_to 'Terms', terms_path %> | <%= link_to 'About', about_path %></h2>


    </div>

    <div class="col-xs-3">
    </div>
</div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<br>



  <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="row">
    <h1> About us</h1>
  </div>
  <div class="row">

    <div class="col-xs-3">
    </div>

    <div class="col-xs-6">
      <b>lorem</b>
      <br>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </div>

    <div class="col-xs-3">
    </div>
  </div>

</div>

app/views/pages/abouthtml.erb
<h1> About us</h1>


<!--localhost:3000/about-->

app/views/pages/terms.html.erb
<div class="container">
  <div class="row">
    <h1> Terms and conditions</h1>
  </div>
  <div class="row">

    <div class="col-xs-3">
    </div>

    <div class="col-xs-6">
      <h4> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </h4>
      Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
      <
      <h4> but.... </h4>

      "But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"
    </div>

    <div class="col-xs-3">
    </div>
  </div>

</div>